### ISSUE TITLE
Error executing action `install` on resource 'package[subversion]' 

### ISSUE THREAD

**Issue by hc000** [opscode-cookbooks/subversion#17]
Hello All,

I am running into this issue when trying to run the subversion cookbook.

Has anyone seen this issue or know whats causing it?

[trainer@sandbox tmp]$ sudo chef-client -zj /tmp/cookbooks/attribute.json 
[sudo] password for trainer: 
[2015-04-02T12:53:05-04:00] WARN: No config file found or specified on command line, using command line options. 
Starting Chef Client, version 11.16.4 
resolving cookbooks for run list: ["subversion"] 
Synchronizing Cookbooks: 
  - subversion 
  - logrotate 
  - apache2 
  - pacman 
  - windows 
  - iptables 
  - chef_handler 
Compiling Cookbooks... 
Converging 3 resources 
Recipe: subversion::client 
  * package[subversion] action install 
 
   
    Error executing action `install` on resource 'package[subversion]' 
    
    Chef::Exceptions::Exec 

     returned 1, expected 0 
 
    Resource Declaration: 

     In /root/.chef/local-mode-cache/cache/cookbooks/subversion/recipes/client.rb 
 
     32:   package 'subversion' do 
     33:     action :install 
     34:   end 
     35: 
 
    Compiled Resource: 
 
     Declared in /root/.chef/local-mode-cache/cache/cookbooks/subversion/recipes/client.rb:32:in `from_file' 
 
    package("subversion") do 
      action [:install] 
      retries 0 
      retry_delay 2 
      guard_interpreter :default 
      package_name "subversion" 
      version "1.6.11-10.el6_5" 
      timeout 900 
      cookbook_name "subversion" 
      recipe_name "client" 
    end 
 
 
Running handlers: 
[2015-04-02T12:53:23-04:00] ERROR: Running exception handlers 
Running handlers complete 
[2015-04-02T12:53:23-04:00] ERROR: Exception handlers complete 
[2015-04-02T12:53:23-04:00] FATAL: Stacktrace dumped to /root/.chef/local-mode-cache/cache/chef-stacktrace.out 
Chef Client failed. 0 resources updated in 17.780396119 seconds 
[2015-04-02T12:53:24-04:00] ERROR: package[subversion] (subversion::client line 32) had an error: Chef::Exceptions::Exec:  returned 1, expected 0 
[2015-04-02T12:53:24-04:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)

**Comment by ZedCode** [comment]
I'm having a similar issue and it seems to be that on rhel subversion-devel is not the correct way to install the subversion client. I edited the line for rhel in the `subversion/recipies/client.rb` recipe from:
```
  extra_packages = value_for_platform_family(
    'debian' => %w[subversion-tools libsvn-perl],
    %w[rhel fedora suse] => %w[subversion-devel subversion-perl],
  )
```
to:
```
  extra_packages = value_for_platform_family(
    'debian' => %w[subversion-tools libsvn-perl],
    %w[fedora suse] => %w[subversion-devel subversion-perl],
    %w[rhel] => %w[svn]
  )
```
This solved the issue for me. Trying to do a `sudo yum install subversion-devel` on RHEL 6.5 fails saying there's no such package.

**Comment by hc000** [comment]
thanks!
